import { GOOGLE_SEARCH_API_KEY, OPEN_WEATHER_MAP_KEY } from "@env";

const GOOGLE_KEY = `${GOOGLE_SEARCH_API_KEY}`;
const OPEN_WEATHER_KEY = `${OPEN_WEATHER_MAP_KEY}`;

export { GOOGLE_KEY, OPEN_WEATHER_KEY };
